### PR TITLE
Small fix to catch more functions and generate prototypes for them

### PR DESCRIPTION
**Pull request by sebastianherp**
Was trying to compile MultiWii (http://code.google.com/p/multiwii/) with arduino-cmake, but it missed some functions because of the indentations.

### CODE REVIEW

**Comment by queezythegreat** [comment]
Hi, thanks for the patch, I will test out your changes and merge it in.

**Comment by queezythegreat** [comment]
I just integrated your changes into the develop branch, please take a took at it. I was able to build two of the sketches (LEDRing and MultiWii_shared). I improved patch a little bit when it comes to ignoring the if else statement. Thanks again for the patch.

**Comment by queezythegreat** [comment]
Closing this ticket, the fix has been integrated and is available in the develop branch.

**Comment by sebastianherp** [comment]
Works, thanks ;-)

**Pull request closed without merging**
