### PR TITLE
Added some features to support pure AVR (non-Arduino) usage

### PR DESCRIPTION
**Pull request by igormiktor**
Hi Tomasz,

First of all, thank you very much for arduino-cmake.  It is wonderful!

I end up doing more and more pure AVR (non-Arduino) coding.  Your toolset works great for doing this kind of work, simply using the NO_AUTOLIBS and MANUAL options.  It is better than any of the other AVR toolchains, especially as I can use a single toolchain to work in either Arduino or AVR mode.  

Still, I've worked it long enough that I wanted to recommend some changes to make this usage even easier and pass them for your consideration.  Please look at branch "igor" in my forked version of your repository.

There are 4 distinct, independent commits that do the following:

1 - Fix minor errors in the documentation that appears in the comments section of your code
2 - Changes the size reporting to report on both fimware and eeprom image sizes and provide the more detailed by section information
3 - Change the upload target so that it uploads both firmware and eeprom images
4 - Adds two new functions, generate_avr_firmware() and generate_avr_library() that work just like generate_arduino_XXX() except that you don't pass NO_AUTOLIBS or MANUAL -- these options are implied.  I coded these functions to just call the corresponding generate_arduino_XXX() functions appending the NO_AUTOLIBS and MANUAL arguments.

I'm not very experienced with CMake, so pehaps there are better ways to code the functions in patch 4.

Thanks for considering these changes.

Igor

igormt@alumni.caltech.edu

### CODE REVIEW

**Comment by queezythegreat** [comment]
Hi, I'm glad you like my project and thanks for contributing!

I'll have a look at your changes when I have some free time.

Initailly everything looks good, I might change the way you have implemented those generate_XXX functions other than that everything looks great.

**Comment by igormiktor** [comment]
Hi Tomasz,

Thanks.

I'm not surprised you'll improve on my implementation of the 
generate_XXX functions -- my knowledge of CMake is limited 
(as is probably obvious :)

Thanks again for creating arduino-cmake.

Igor

**Comment by queezythegreat** [comment]
Hi,

I haven't been around for the last couple of months (I was very busy with work), and I completely forgot about your patch. I will be doing some integration work on Arduino CMake in a couple of days, and I will try to get your patch integrated. 

Sorry for not responding.

**Comment by igormiktor** [comment]
No worries!

Igor

**Comment by queezythegreat** [comment]
I just integrated your changes into the develop branch, could you please look at it.

I'm not sure if everything merged in correctly. The size reporting script has changed since your changes where made, please confirm it reports the correct values.

Also could you please provide a pure avr example, I still want to cleanup the generate_avr_\* command but I don't have a good example. Thanks for contributing, and sorry for the loooooong delay :)

**Comment by igormiktor** [comment]
I'm traveling right now, but I can test and get you an 
example over the weekend.  Hope that is okay.

Igor

**Comment by queezythegreat** [comment]
Great, no worries I can wait :)

**Comment by igormiktor** [comment]
Sorry!  Got wrapped up in a zillion things when I got back 
from my trip and completely forgot about this.

Attached is a very simple pure avr example that you can use 
for testing.

Note that you'll need to tweak the setting for 
CMAKE_TOOLCHAIN_FILE in the CMakeLists.txt file.

I'm buried with work this week, but I really promise to test 
the new changes you made this weekend.

Igor

**Comment by queezythegreat** [comment]
Hi, I don't see anything attached.

**Comment by igormiktor** [comment]
Here it is.  Sorry.

Igor

**Comment by queezythegreat** [comment]
Hi, are you attaching the code via email? I don't think GitHub allows email attachments, because I still don't see anything.

**Comment by igormiktor** [comment]
I just reply to the email....

You can grab the file here:

https://dl.dropboxusercontent.com/u/88651249/arduino-plain.tar.gz

Igor

**Comment by queezythegreat** [comment]
Thanks! I will have a look at it when I have some free time.

**Pull request merged**
